In [2]:
import numpy as np

## Generating Data

In [3]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
height

array([1.71, 1.84, 1.58, ..., 1.8 , 1.6 , 1.75])

In [4]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
weight

array([38.13, 43.81, 59.65, ..., 58.17, 54.08, 62.39])

In [5]:
np_city = np.column_stack((height, weight))
np_city

array([[ 1.71, 38.13],
       [ 1.84, 43.81],
       [ 1.58, 59.65],
       ...,
       [ 1.8 , 58.17],
       [ 1.6 , 54.08],
       [ 1.75, 62.39]])

## *Creating a Numpy Array using a List*

In [6]:
a_list = [3,4,5]
np.array(a_list)

array([3, 4, 5])

## Creating array of linearly-spaced elements
### Starting with 0, ending at 30, stepping by 2

In [7]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## Creating an array by dividing a range into a number of parts
### starting with 0 and ending at 15, divided into 5 elements

In [8]:
np.linspace(0,15,5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

## Creating a 2D array of 3rows, 3cols with normally distributed random values
### mean at 0 and standard deviation 1

In [9]:
np.random.normal(0,1,(3,3))

array([[-0.58927266, -0.91339482, -0.43925185],
       [ 0.71885713,  0.16303394, -1.64052602],
       [ 1.24897366,  0.73504868,  0.68421436]])

## Useful array attributes

In [24]:
#Iterating over a numpy N Dimensional array

array_2D = np.random.randint(10, size=(4,5))
print(array_2D)

for item in np.nditer(array_2D):
    print(item)

[[4 2 0 3 2]
 [0 7 5 9 0]
 [2 7 2 9 2]
 [3 3 2 3 4]]
4
2
0
3
2
0
7
5
9
0
2
7
2
9
2
3
3
2
3
4


In [11]:
# Set a seed value to generate same random values on every run
np.random.seed(0)

# Create 3 arrays(1D, 2D & 3D)
arr1 = np.random.randint(10, size=6)
arr2 = np.random.randint(10, size=(3,4))
arr3 = np.random.randint(10, size=(3,4,5))

In [12]:
print(arr1, arr2, arr3, sep="\n")

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [13]:
## printing the dimension, shape, size, and bytes of an array
print("Arr3 type: ", type(arr3))
print("Arr3 ndim: ", arr3.ndim)
print("Arr3 shape: ", arr3.shape)
print("Arr3 size: ", arr3.size)
print("Arr3 bytes: ", arr3.nbytes, "bytes")

Arr3 type:  <class 'numpy.ndarray'>
Arr3 ndim:  3
Arr3 shape:  (3, 4, 5)
Arr3 size:  60
Arr3 bytes:  240 bytes


## Indexing and slicing

In [14]:
print("1D Array: \n", arr1)
print("First element: \n", arr1[0])
print("Last element: \n", arr1[-1])
print("First 3 elements: \n", arr1[:3])
print("Element after 4th index: \n", arr1[4:])
print("Subarray from 3rd index to 7th index: \n", arr1[3:8])
print("Alternate elements: \n", arr1[::2])
print("Reversed array: \n", arr1[::-1])

1D Array: 
 [5 0 3 3 7 9]
First element: 
 5
Last element: 
 9
First 3 elements: 
 [5 0 3]
Element after 4th index: 
 [7 9]
Subarray from 3rd index to 7th index: 
 [3 7 9]
Alternate elements: 
 [5 3 7]
Reversed array: 
 [9 7 3 3 0 5]


In [15]:
print("2D Array: \n", arr2)
print("2nd Element of the 3rd row: \n", arr2[2,1])
print("Slicing the array to get 2nd and 3rd rows: \n", arr2[1:3,:] )
print("Alternate columns: \n", arr2[:,::2])

2D Array: 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
2nd Element of the 3rd row: 
 6
Slicing the array to get 2nd and 3rd rows: 
 [[7 6 8 8]
 [1 6 7 7]]
Alternate columns: 
 [[3 2]
 [7 8]
 [1 7]]


## Basic Statistics

In [16]:
# Average or Mean
np.mean(arr2[:,0])

3.6666666666666665

In [17]:
# Sort and the middle value
np.median(arr3[:,:,0])

5.0

In [18]:
# Co Relation between first and second column
np.corrcoef(arr2[:,0], arr2[:,1])

array([[1.        , 0.18898224],
       [0.18898224, 1.        ]])

In [19]:
# Standard deviation
np.std(arr3[:,:,0])

2.8999521068842196

In [20]:
pass

In [21]:
#sum
np.sum(arr3)

263

In [22]:
print(arr3)
print(np.sort(arr3))

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
[[[1 5 8 8 9]
  [0 3 3 4 9]
  [0 2 3 5 8]
  [1 3 3 3 7]]

 [[0 0 1 9 9]
  [2 3 4 7 7]
  [0 0 2 4 5]
  [1 4 5 6 8]]

 [[1 1 4 8 9]
  [3 6 7 9 9]
  [0 2 3 5 7]
  [4 4 4 6 9]]]
